"""vpn_profile_server_nullable_set_null

Revision ID: cb003b55f70f
Revises: 
Create Date: 2026-03-02 11:57:53.949505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb003b55f70f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vpn_profiles', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('vpn_profiles_server_id_fkey', 'vpn_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'vpn_profiles', 'servers', ['server_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vpn_profiles', type_='foreignkey')
    op.create_foreign_key('vpn_profiles_server_id_fkey', 'vpn_profiles', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vpn_profiles', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
